name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    container:
      image: ghcr.io/mrombout/asciihero-test:main

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm link
      - run: npm ci
      - run: npm test
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: Example Diffs
          path: examples/**/*.png
